version: '3'

services:
  database:
    image: postgres
    container_name: challenge-task-devEmTreinamento
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/database-docker:/var/lib/postgresql/data 
 